# ----- Base -----------------------------------------------------------------------------------------------------------
x-base-config: &x-base-config
  image: marketplace-backend:latest
  env_file: ../.env
  restart: always


# ----- Healthcheck ----------------------------------------------------------------------------------------------------
x-healthcheck: &x-healthcheck
  start_period: 30s
  interval: 30s
  timeout: 10s
  retries: 5

x-postgres-healthcheck: &x-postgres-healthcheck
  test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -h postgres -p 5432" ]
  <<: *x-healthcheck

x-redis-healthcheck: &x-redis-healthcheck
  test: [ "CMD-SHELL", "redis-cli", "ping" ]
  <<: *x-healthcheck

x-backend-healthcheck: &x-backend-healthcheck
  test: [ "CMD-SHELL", "python", "manage.py", "check" ]
  <<: *x-healthcheck

x-rabbitmq-healthcheck: &x-rabbitmq-healthcheck
  test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
  <<: *x-healthcheck


# ----- Services -------------------------------------------------------------------------------------------------------
services:

  # --- Postgres -------------------------------------------------------------------------------------------------------
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck: *x-postgres-healthcheck
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - logs:/var/log/postgresql


  # --- Redis ----------------------------------------------------------------------------------------------------------
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    healthcheck: *x-redis-healthcheck
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data


  # --- Backend --------------------------------------------------------------------------------------------------------
  backend:
    <<: *x-base-config
    container_name: backend
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    healthcheck: *x-backend-healthcheck
    ports:
      - ${DJANGO_PORT}:8000
    volumes:
      - ./:/code/
      - logs:/var/log/backend/django


  # --- RabbitMQ -------------------------------------------------------------------------------------------------------
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck: *x-rabbitmq-healthcheck
    ports:
      - "5672:5672"
      - "15672:15672"  # For the web administration panel
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


  # --- Celery ---------------------------------------------------------------------------------------------------------
  celery-beat:
    <<: *x-base-config
    container_name: celery-beat
    command: celery -A config beat --loglevel=info
    volumes:
      - ./:/code/
      - logs:/var/log/backend/celery/beat

  celery-worker-low-priority:
    <<: *x-base-config
    container_name: celery-worker-low-priority
    command: celery -A config worker --loglevel=info --autoscale=4,0 --max-tasks-per-child=10 --queues=low_priority
    volumes:
      - ./:/code/
      - logs:/var/log/backend/celery/worker

  celery-worker-high-priority:
    <<: *x-base-config
    container_name: celery-worker-high-priority
    command: celery -A config worker --loglevel=info --autoscale=10,1 --max-tasks-per-child=50 --queues=high_priority
    volumes:
      - ./:/code/
      - logs:/var/log/backend/celery/worker
